### ISSUE TITLE
segfault while installing

### ISSUE THREAD

**Issue by gaiazaff** [GuangchuangYu/DOSE#25]
I updated Bioconductor and I am using a fairly recent R version, but still I cannot install DOSE; I get the error:

> biocLite("DOSE")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.0 (2017-04-21).
Installing package(s) 'DOSE'
trying URL 'https://bioconductor.org/packages/3.6/bioc/src/contrib/DOSE_3.4.0.tar.gz'
Content type 'application/x-gzip' length 7573499 bytes (7.2 MB)
==================================================
downloaded 7.2 MB

* installing *source* package 'DOSE' ...
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded

 *** caught segfault ***
address (nil), cause 'memory not mapped'
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault
ERROR: loading failed
* removing '/mnt/gaiagpfs/users/homedirs/gzaffaroni/R/x86_64-pc-linux-gnu-library/3.4/DOSE'

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: q("no", status = status, runLast = FALSE)
 2: do_exit(status = status)
 3: do_exit_on_error()
 4: errmsg("loading failed")
 5: do_install_source(pkg_name, instdir, pkg, desc)
 6: do_install(pkg)
 7: tools:::.install_packages()
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault

The downloaded source packages are in
        '/tmp/RtmpaXc0RQ/downloaded_packages'
Warning message:
In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package 'DOSE' had non-zero exit status

**Comment by GuangchuangYu** [comment]
did you upgrade gcc recently?

it seems that you're running into old vs. new compiler issues.

**Comment by gaiazaff** [comment]
I will check with the admins of the server, thanks.

**Comment by igordot** [comment]
If the issue is with the gcc upgrade, what is the appropriate solution? If a package can't load, you would reinstall it. But if a package can't install, then what should be done? Do some R settings need to be modified?

**Comment by NingxiaoMo** [comment]
HI, I have met the same problem as you, want to ask how did you solve it?
As I have tried a lot of methods ,such as using a new version R ,biocLite("DO.db"),and they are useless.

**Comment by gaiazaff** [comment]
I decided to use something else, because I didn't get any feedback from my admins.
Sorry I cannot be more useful.

**Comment by igordot** [comment]
I tried to determine the problematic dependency and ended up recompiling all my packages. That was not the optimal solution, but it solved the problem. If you don't have root access, the packages will end up installed in your home directory. Bioconductor provides a simple method to reinstall all packages from source:
```
source("https://bioconductor.org/biocLite.R")
pkgs <- rownames(installed.packages())
biocLite(pkgs, type="source")
```
Source: https://www.bioconductor.org/install/ (Recompiling installed Bioconductor packages section)

**Comment by NingxiaoMo** [comment]
Y叔您好，在尝试了您的方法把依赖的包更新之后，还是没有解决；附件是DOSE包的安装失败的结果，clusterprofiler的结果还是和之前一样无法安装，如果真的装不上，斗胆问下您有没有其他的推荐的包呢？

 
 
------------------ Original ------------------

**Comment by dnebdal** [comment]
This happens to me as well. R 3.5.1 on FreeBSD 11.1, from packages (so presumably compiled with clang 4.0.0). If I install DOSE from bioconductor, I get the same segfault on install, but it otherwise seems to work. However, if I load DOSE, R segfaults on exit. 

I started R in gdb to see if that would help in understanding this. I'm not sure how informative it is, but it does seem to point at RSQLite?
`Save workspace image? [y/n/c]: n

Program received signal SIGSEGV, Segmentation fault.
0x0000004104211607 in std::__1::(anonymous namespace)::__libcpp_atomic_add<long, int> (__a=-1, 
    __order=4, __val=<optimized out>) at /usr/src/contrib/libc++/src/include/atomic_support.h:82
82      /usr/src/contrib/libc++/src/include/atomic_support.h: No such file or directory.
(gdb) bt
#0  0x0000004104211607 in std::__1::(anonymous namespace)::__libcpp_atomic_add<long, int> (__a=-1, 
    __order=4, __val=<optimized out>) at /usr/src/contrib/libc++/src/include/atomic_support.h:82
#1  std::__1::(anonymous namespace)::decrement<long> (t=<optimized out>)
    at /usr/src/contrib/libc++/src/memory.cpp:37
#2  std::__1::__shared_count::__release_shared (this=0x0) at /usr/src/contrib/libc++/src/memory.cpp:65
#3  0x000000410ace80d0 in Rcpp::Rostream<false>::~Rostream() ()
   from /usr/local/lib/R/library/RSQLite/libs/RSQLite.so
#4  0x0000004101600a01 in __cxa_finalize (dso=0x0) at /usr/src/lib/libc/stdlib/atexit.c:235
#5  0x00000041015915d1 in exit (status=0) at /usr/src/lib/libc/stdlib/exit.c:72
#6  0x0000004100c438dd in ?? () from /usr/local/lib/R/lib/libR.so.3.5
#7  0x0000004100b5fc42 in ?? () from /usr/local/lib/R/lib/libR.so.3.5
#8  0x0000004100b20ab1 in ?? () from /usr/local/lib/R/lib/libR.so.3.5
#9  0x0000004100b1b7ca in Rf_eval () from /usr/local/lib/R/lib/libR.so.3.5
#10 0x0000004100b2cdb8 in ?? () from /usr/local/lib/R/lib/libR.so.3.5
#11 0x0000004100b1baba in Rf_eval () from /usr/local/lib/R/lib/libR.so.3.5
#12 0x0000004100b5defc in Rf_ReplIteration () from /usr/local/lib/R/lib/libR.so.3.5
#13 0x0000004100b5f3df in run_Rmainloop () from /usr/local/lib/R/lib/libR.so.3.5
#14 0x000000000040094b in main ()
(gdb) 
`

**Comment by GuangchuangYu** [comment]
@dnebdal did you try installing RSQLite from source?
